// Generate complete HTML in both languages; no client-side translation or build dependencies.
import { readFile, writeFile, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { locales, project, release, download, commands } from '../content/site.mjs';
import { buildMediaGuide } from './build-media-guide.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const media = JSON.parse(await readFile(resolve(root, 'content/media.json'), 'utf8'));
await buildMediaGuide(root, media);
const escape = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const exists = async (path) => { try { await access(resolve(root, path)); return true; } catch { return false; } };
const link = (url, text, cls = '') => `<a${cls ? ` class="${cls}"` : ''} href="${escape(url)}">${escape(text)}</a>`;
const heading = (label, title) => `<div class="section-heading"><p class="section-label">${escape(label)}</p><h2>${escape(title)}</h2></div>`;
const cards = (items, cls = '') => `<div class="focus-grid ${cls}">${items.map(([title, copy]) => `<article><h3>${escape(title)}</h3><p>${escape(copy)}</p></article>`).join('')}</div>`;
const steps = (items) => `<ol class="focus-grid beginner-grid setup-steps">${items.map(([title, copy], i) => `<li><span class="step-number">0${i + 1}</span><h3>${escape(title)}</h3><p>${escape(copy)}</p></li>`).join('')}</ol>`;

async function figure(id, locale, hero = false) {
  const item = media.find(item => item.id === id);
  const t = locales[locale];
  const ready = await exists(item.file);
  let visual;
  if (ready && item.type === 'image') {
    visual = `<img src="${item.file}" alt="${escape(item.alt[locale])}" width="${item.width}" height="${item.height}" ${hero ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
  } else if (ready) {
    const hasPoster = await exists(item.poster);
    const tracks = [];
    for (const [lang, path] of Object.entries(item.captions)) {
      if (await exists(path)) tracks.push(`<track kind="captions" src="${path}" srclang="${locales[lang].lang}" label="${lang === 'en' ? 'English' : 'Português (Brasil)'}"${lang === locale ? ' default' : ''}>`);
    }
    visual = `<video controls playsinline preload="none" width="${item.width}" height="${item.height}" aria-label="${escape(item.alt[locale])}"${hasPoster ? ` poster="${item.poster}"` : ''}><source src="${item.file}" type="video/mp4">${tracks.join('')}<p>${escape(t.videoFallback)} ${link(item.file, t.videoDownload)}</p></video>`;
  } else {
    // Missing assets are intentional. Do not request nonexistent URLs or show broken media controls.
    visual = `<div class="media-placeholder" role="img" aria-label="${escape(t.mediaSoon + '. ' + item.alt[locale])}" style="--media-ratio:${item.width}/${item.height}">
      <span class="placeholder-corner" aria-hidden="true">${item.type === 'video' ? '▶' : '◇'} ${escape(t[item.type])}</span>
      <div class="placeholder-scene" aria-hidden="true"><span></span><span></span><span></span></div>
      <div class="placeholder-copy" aria-hidden="true"><span class="section-label">${escape(t.mediaSoon)}</span><strong>${escape(item.title[locale])}</strong><code>${escape(item.file)}</code><small>${item.width} × ${item.height}${item.type === 'video' ? ' · MP4' : ' · WebP'}</small></div>
    </div>`;
  }
  const transcript = ready && item.type === 'video' && await exists(item.transcripts[locale]) ? ` ${link(item.transcripts[locale], t.transcript, 'text-link')}` : '';
  const music = ready && item.music ? `<small class="media-credit">${t.musicCredit}: ${link(item.music.url, item.music.title + ' — ' + item.music.artist)} · ${link(item.music.licenseUrl, item.music.license)}</small>` : '';
  return `<figure class="media-frame${hero ? ' media-frame--hero' : ''}" data-media="${id}" data-state="${ready ? 'ready' : 'placeholder'}">${visual}<figcaption><span>${escape(item.title[locale])}</span>${transcript}${music}</figcaption></figure>`;
}

for (const [locale, t] of Object.entries(locales)) {
  const doc = (page) => `${project}/blob/main/docs/${t.docs}/${page}.md`;
  const docs = `${project}/blob/main/docs/README${t.suffix}.md`;
  const file = (name) => `${project}/blob/main/${name}${t.suffix}.md`;
  const logo = '<img src="assets/icon.svg" alt="" width="40" height="40">';
  const html = `<!doctype html>
<!-- Adapted from Gravewright repository-site. See THIRD_PARTY_NOTICES.md. Generated by scripts/build.mjs. -->
<html lang="${t.lang}" class="no-js">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escape(t.title)}</title><meta name="description" content="${escape(t.description)}">
  <meta name="theme-color" content="#0b0d10"><meta property="og:type" content="website">
  <meta property="og:title" content="${escape(t.title)}"><meta property="og:description" content="${escape(t.description)}">
  <meta property="og:locale" content="${locale === 'en' ? 'en_US' : 'pt_BR'}">
  <link rel="alternate" hreflang="en" href="index.html"><link rel="alternate" hreflang="pt-BR" href="pt-br.html">
  <link rel="icon" href="assets/icon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css">
  <script src="script.js" defer></script>
</head>
<body data-copy-label="${t.copy}" data-copied-label="${t.copied}" data-selected-label="${t.selected}" data-copied-message="${escape(t.copiedMessage)}" data-selected-message="${escape(t.selectedMessage)}">
<a class="skip-link" href="#main-content">${t.skip}</a>
<header class="site-header" data-header><div class="shell header-inner">
  <a class="brand" href="#top" aria-label="${t.home}"><span class="brand-icon">${logo}</span><span>Gravewright</span></a>
  <button class="menu-toggle" type="button" aria-controls="main-nav" aria-expanded="false" data-menu-toggle><span></span><span></span><span class="sr-only">${t.menu}</span></button>
  <nav class="main-nav" id="main-nav" aria-label="${t.navigation}" data-nav>
    ${['experience','release','install','contribute'].map((id, i) => link('#' + id, t.nav[i])).join('')}
    <a class="language-link" href="${t.otherFile}" lang="${locale === 'en' ? 'pt-BR' : 'en'}" hreflang="${locale === 'en' ? 'pt-BR' : 'en'}" data-language>${t.otherLabel}</a>
    ${link(project, 'GitHub ↗', 'nav-button')}
  </nav>
</div></header>
<main id="main-content">
  <section class="hero shell" id="top">
    <div class="hero-copy"><p class="eyebrow">${t.eyebrow}</p><div class="hero-brand"><span class="hero-icon">${logo}</span><h1>Gravewright</h1></div>
      <p class="hero-lead">${t.lead}</p><p class="hero-meta">${t.intro}</p>
      <div class="hero-actions">${link(download, t.download, 'button button-primary')}${link('#experience', t.explore, 'button button-secondary')}</div>
      <p class="download-hint">${t.downloadHint}</p><div class="quick-links">${link(release, t.notes + ' ↗')}${link(docs, t.documentation + ' ↗')}</div>
    </div>
    <aside class="hero-panel" aria-label="${t.panelAria}"><div class="panel-topline"><span>${t.panelLabel}</span><span class="status"><i></i> Alpha</span></div>
      <div class="platform-list">${t.pillars.map(([title, copy], i) => `<article><span>0${i+1}</span><div><h2>${title}</h2><p>${copy}</p></div></article>`).join('')}</div>
    </aside>
  </section>
  <div class="media-showcase shell">${await figure('table', locale, true)}</div>
  <section class="section shell" id="about">${heading(t.aboutLabel, t.aboutTitle)}<div class="section-copy"><p>${t.aboutCopy}</p></div>${cards(t.features)}</section>
  <section class="section shell" id="experience">${heading(t.experienceLabel, t.experienceTitle)}<div class="section-copy"><p>${t.experienceCopy}</p></div>
    ${await figure('session', locale)}<div class="focus-grid beginner-grid">${t.roles.map(([label, title, copy]) => `<article><span class="step-number">${label}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div>
  </section>
  <section class="section shell" id="characters">${heading(t.sheetsLabel, t.sheetsTitle)}<div class="section-copy"><p>${t.sheetsCopy}</p></div>${await figure('sheet', locale)}</section>
  <section class="section shell" id="release">${heading(t.releaseLabel, t.releaseTitle)}<div class="section-copy"><p>${t.releaseCopy}</p>${link(release, t.notes + ' ↗', 'text-link')}</div>${await figure('campaign', locale)}${cards(t.releaseFeatures)}</section>
  <section class="section shell" id="install">${heading(t.installLabel, t.installTitle)}<div class="section-copy"><p>${t.installCopy}</p><p class="requirements-line">${t.requirement}</p></div>
    ${steps(t.steps)}<div class="install-actions">${link(download, t.download, 'button button-primary')}${link(doc('windows-runner'), t.runnerGuide + ' ↗', 'text-link')}</div>
    <aside class="hosting-note"><h3>${t.localTitle}</h3><p>${t.localCopy}</p>${link(doc('deployment'), t.deployment + ' ↗', 'text-link')}</aside>
    <div class="install-layout"><div class="install-copy"><p class="section-label">${t.sourceLabel}</p><h3>${t.sourceTitle}</h3><p>${t.sourceCopy}</p></div>
      <div class="terminal"><div class="terminal-header"><span>${t.sourceHeader}</span><button type="button" data-copy="source">${t.copy}</button></div>
      <pre tabindex="0"><code data-code="source">${escape(commands)}</code></pre><div class="terminal-footer"><a href="http://127.0.0.1:3000">http://127.0.0.1:3000</a></div></div>
    </div>
  </section>
  <section class="section shell" id="extensions">${heading(t.extensionsLabel, t.extensionsTitle)}<div class="section-copy"><p>${t.extensionsCopy}</p><div class="quick-links">${link(doc('api'), t.api + ' ↗')}${link(doc('modules'), t.modules + ' ↗')}</div></div>
    <div class="license-card"><span class="license-mark" aria-hidden="true">&lt;/&gt;</span><div><h3>${t.licenseTitle}</h3><p>${t.licenseCopy}</p>${link(file('LICENSING'), t.licensing + ' ↗', 'text-link')}</div></div>
  </section>
  <section class="section shell" id="questions">${heading(t.faqLabel, t.faqTitle)}<div class="faq-list">${t.faq.map(([q, a]) => `<details><summary>${escape(q)}</summary><p>${escape(a)}</p></details>`).join('')}</div></section>
  <section class="section shell" id="contribute">${heading(t.contributeLabel, t.contributeTitle)}<div class="contribute-layout"><p class="contribution-copy">${t.contributeCopy}</p><div class="resource-card">${link(file('CONTRIBUTING'), t.contribute + ' ↗')}${link(docs, t.documentation + ' ↗')}${link(project + '/issues', t.issues + ' ↗')}${link(file('SECURITY'), t.security + ' ↗')}</div></div></section>
  <section class="final-cta shell"><span class="hero-icon">${logo}</span><div><p class="section-label">${t.finalLabel}</p><h2>${t.finalTitle}</h2></div>${link(download, t.download, 'button button-primary')}</section>
</main>
<footer class="site-footer"><div class="shell footer-inner"><div><a class="brand footer-brand" href="#top">Gravewright</a><p>${t.footer}</p></div><p>Alpha 0.1.0 · ${link(file('LICENSING'), locale === 'en' ? 'GPL-3.0-only + module permission' : 'GPL-3.0-only + permissão para módulos')}</p>${link('#top', t.top + ' ↑')}</div></footer>
<div class="toast" role="status" aria-live="polite" data-toast></div>
</body></html>
`;
  await writeFile(resolve(root, t.file), html);
  console.log(`Generated ${t.file}`);
}
